### ISSUE TITLE
ojAlgo v43 api

### ISSUE THREAD

**Issue by luke777** [sashee/lp_ip_java_sample#2]
Thanks for the useful example.  

I noticed that with  ojAlgo v43 the api is slightly different.  It looks like
expression.setLinearFactor(variables.get(0), 6);
needs to be changed to 
expression.set(variables.get(0), 6);

**Comment by sashee** [comment]
Thanks for letting me know! I've updated the dependency and the code samples both on GitHub and on the website. Furthermore, I've noticed that ojAlgo is now in central, so adding a repository is no longer needed.

I wrote that article more than two years ago, and I'm glad people like you still find it useful.
